# Generated by Django 5.2.8 on 2026-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_returnrequest_order_pickup_date_status_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('pickup_in_progress', 'Pickup In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
